---
- name: K10 Location Profile Creation
  hosts: localhost
  vars:
    s3bucket: "pcerda-k10immutable"
    k10_ns: "kasten-io"
  collections:
    - kubernetes.core
  tasks:
    - name: Get all namespaces with restorepoints
      shell:
         "kubectl get restorepoints.apps.kio.kasten.io -A | awk '{print $1}' | sort | uniq"
      register: appnspaces

    - name: restore cluster resources
      include_tasks: restoreapps/runrestorecluster.yaml      
      
    - name: Creating list of namespaces
      ansible.builtin.set_fact:
        one_list: appnspaces.stdout_lines | list
    
    - name: Restore all apps
      include_tasks: restoreapps/runrestoreapp.yaml
      loop: "{{ appnspaces.stdout_lines | list }}"
      loop_control:
        loop_var: nspace

      


      
